# en-US
ConvertFrom-StringData @'
AuthModeMessage                  = Executing Azucar with {0} authentication flow
ExpiredTokenMessage				 = There was an error with TokenCache which expires on {0}. Trying to refresh token
InvalidIEVersion                 = Internet Explorer 11 or later required. Current IE version is {0}
InvalidDirectoryPathError        = Path {0} is not a valid directory path
InvalidPowerShellVersion         = PowerShell V2 detected. This script requires Windows PowerShell version 3.0 or above.
GenericPowerShellErrorVersion    = This script requires Windows PowerShell version 3.0 or above.
InvalidNETVersion                = This script requires Microsoft .NET Framework 4.5 or above.
RetrieveResourceGroups           = Retrieving resource groups for the subscription {0}
ResourceGroupsRetrieveError      = Unable to retrieve resource groups....
ReportFolderInitMessage          = Trying to create a report folder....
ReportFolderMessageCreation      = Report folder created in {0}...
TimeElapsedScript                = Total time for JOBs: {0} Minutes
FolderReportMessageCreation      = Folder Reports created in {0}...
DirectoryAlreadyExistsWarning    = Directory {0} already exists....
CSVTaskCreateReportMessage       = CSV Task: Generating CSV report for data retrieved from {0}
EXCELTaskCreateReportMessage     = Excel Task: Generating Excel report for data retrieved from {0}
JSONTaskCreateReportMessage      = JSON Task: Generating JSON report for data retrieved from {0}
XMLTaskCreateReportMessage       = XML Task: Generating CSV report for data retrieved from {0}
ExportFileToCSVMessage           = Export {0} to CSV file
ExportFileToJSONMessage          = Export {0} to JSON file
ExportFileToXMLMessage           = Export {0} to XML file
UnableToCreateAzucarObject       = Unable to create new object {0}
ExcelLocaleDetected              = Locale {0} detected...
ExcelExportToANewSheetMessage    = Export {0} to a new sheet
CheckTenantIDMessage             = Check tenantID {0}
LoginAzureTenantMesssage         = Login to Azure Active Directory using TenantID {0}
LoginAzureRMMesssage             = Login to Azure Resource Manager using TenantID {0}
LoginAzureSMMesssage             = Login to Azure Service Management using TenantID {0}
DirectoryAlreadyExistsMessage    = Directory {0} already exists....
FolderCreatedMessage             = Folder created in {0}....
IESettingsHTTPMessage            = Setting default webbroser IE.HTTP for HTTP...
IESettingsHTTPSMessage           = Setting default webbroser IE.HTTPS for HTTPS...
ConnectionAzureRMErrorMessage    = Not connected to an Azure Resource Manager tenant.
ConnectionAzureADErrorMessage    = Not connected to an Azure Active Directory tenant.
ConnectionAzureSMErrorMessage    = Not connected to an Azure Service Management tenant.
GetRequestObjectMessage          = Get request for object type {0} succeeded.
AddAzucarPluginNameMessage       = Adding {0} to queue....
AzureADUserSearchReturn          = The users search return {0}
AzureADAuditSearchReturn         = The audit log search return {0}
AzureADContactsSearchReturn      = The contacts search return {0}
AzureADGroupSearchReturn         = The group search return {0}
AzureADDirectorySearchReturn     = The Directory roles search return {0}
AzureADDomainSearchReturn        = The domain search return {0}
AzureADUsersQueryEmptyMessage    = The Users query did not return any data in {0} tenant
AzureADAuditQueryEmptyMessage    = The Audit query did not return any data in {0} tenant
AzureADPoliciesQueryEmptyMessage = The Policies query did not return any data in {0} tenant
AzureADGroupsQueryEmptyMessage   = The Groups query did not return any data in {0} tenant
AzureADDomainQueryEmptyMessage   = The Domain query did not return any data in {0} tenant
AzureADContactsQueryEmptyMessage = The Contacts query did not return any data in {0} tenant
AzureADRoleMemberQueryEmptyMessage    = The Directory Roles Members query did not return any data in {0} tenant
AzureADRoleQueryEmptyMessage    = The Directory Roles query did not return any data in {0} tenant
AzureADGeneralQueryEmptyMessage  = The {0} query did not return any data in {1} tenant
AzucarADContactTaskMessage       = Contacts task ID {0}: Retrieve {1} from {2} tenant
AzucarADDomainTaskMessage        = Domain task ID {0}: Retrieve {1} from {2} tenant
AzucarADAuditTaskMessage         = Audit task ID {0}: Retrieve {1} from {2} tenant
AzucarADGeneralTaskMessage       = {0} task ID {1}: Retrieve {2} from {3} tenant
AzucarADDirectoryRoleTaskMessage = Directory Roles task ID '{0}': Retrieve '{1}' from '{2}' tenant
AzucarADUsersTaskMessage         = Users task ID {0}: Retrieve {1} from {2} tenant
AzucarADPoliciesTaskMessage      = Policies task ID {0}: Retrieve {1} from {2} tenant
AzucarADGroupsTaskMessage        = Group task ID {0}: Retrieve {1} from {2} tenant
ResourceGroupsLimitScoped        = Will scope analysis to {0} resource group
ResourceGroupsLimitEmpty         = The Resource Group query did not return any valid resource group in {0} tenant
AzUserPermissions                = Trying to get permissions for user {0}
AzRoleBasedPermissions           = Trying to get permissions for roleId {0}
'@;